config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root 'tweets#index'
  get 'tweets/timeline' => 'tweets#timeline'
  get 'users/messages' => 'messages#index'
  post 'users/messages' => 'messages#create'


  resources :tweets do
    resources :comments, only: [:create]

    collection do
      get 'search'
    end

  end

#resources :users, only: [:show, :edit, :update]

#resources :messages, only: [:index, :create]



  resources :users do
    resources :messages, only: [:index, :create]
   end

end



  # get 'tweets' => 'tweets#index'
  # get 'tweets/new' => 'tweets#new'
  # post  'tweets'  => 'tweets#create'
  # delete 'tweets/:id' => 'tweets#destroy'
  # patch 'tweets/:id' => 'tweets#update'
  # get 'tweets/:id/edit' => 'tweets#edit'
  # get 'users/:id' => 'users#show'
  # get 'tweets/:id' => 'tweets#show'

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :tweet
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :sender, class_name: User

  delegate :image, :first_name, to: :sender, prefix: true, allow_nil: true

  def sender
    super || User.new(first_name: "Missing Sender")
  end
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # 以下を追記
  # has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>", small:"45x45>"}, storage: :s3, bucket: S3_BUCKET
  # validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]

  has_many :tweets
  has_many :comments
  has_many :messages

  has_attached_file :image, styles: { medium:"300x300>", thumb:"150x150>", small:"45x45>"},
  :storage =>:s3,
  :bucket => S3_BUCKET,
  :path => ":attachment/:id/:style.:extension",
  :url => ':s3_domain_url',
  :default_url => "no_image.jpg"






  # User.new.image(:small) => "/images/default_small_avatar.png"

  #:url  => "/brali-image/images/:id/:style/:extension"

  # validates_attachment_content_type :image, content_type: ["image/jpg","image/jpeg","image/png"]
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }




  # has_attached_file :image, styles: { medium:"300x300>", thumb:"150x150>", small:"45x45>"} :storage => :s3,
  # :s3_credentials => "#{Rails.root}/config/s3.yml",
  # :path => ":attachment/:id/:style.:extension"

# has_attached_file :avatar, styles: { medium:"300x300>", thumb:"150x150>", small:"45x45>"}
#

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :resource_name, :resource, :devise_mapping

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
   @comment = Comment.create(message: params[:message], tweet_id: params[:tweet_id], user_id: current_user.id)
   


     tweet = Tweet.find(params[:tweet_id])

    redirect_to "/tweets/#{@comment.tweet.id}"

    NoticeMailer.sendmail_confirm(@comment.tweet.id,tweet.user_id,current_user.id).deliver
    #NoticeMailer.sendmail_confirm(current_user.id).deliver
   end


  private
  def comment_params
    params.permit(:message, :tweet_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @user = User.find(params[:user_id])
  end

  def create
    @message = Message.create(message: params[:message], user_id: params[:user_id], sender: current_user)

    user = User.find(params[:user_id])

    redirect_to "/users/#{@message.user_id}/messages"


    #メールのメッセージ（後で考える）
    #NoticeMailer.sendmail_confirm(@comment.tweet.id,tweet.user_id,current_user.id).deliver
  end

  private

  def comment_params
    params.permit(:message, :user_id)
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = FindOrCreateOauthUser.call(auth_data: env['omniauth.auth']).user

    sign_in_and_redirect user, event: :authentication
    set_flash_message(:notice, :success, kind: 'Facebook')
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  # before_action :move_to_index, except: :index
  before_action :move_to_index, except: [:index, :search, :timeline]

  def index
  end

  def new
  end

  def create
    Tweet.create(place: tweet_params[:place], day: tweet_params[:day], message: tweet_params[:message], user_id: current_user.id)
    # Tweet.create(name: params[:name], place: params[:place], day:params[:day], message: params[:message])
  end

  def destroy
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.destroy
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.update(tweet_params)
    end
  end

  def show
     @tweet = Tweet.find(params[:id])
     @comments = @tweet.comments.includes(:user).order("created_at")
  end

  def timeline
    @tweets = Tweet.includes(:user).order("day").page(params[:page]).per(10)
  end

  def form_for
    @place = Place.new
  end
  

 def search
  # @tweets = Tweet.where('place LIKE(?)',"%#{params[:keyword]}%").limit(10)
  puts "KINDは"
  @kind = params[:kind]
  puts @kind

  @tweets = Tweet.where('place LIKE(?)',"%#{params[:keyword]}%").order("day").page(params[:page]).per(5)
  @user = User.find_by(id: @user_id)


  @users = User.where('place LIKE(?)',"%#{params[:keyword]}%").order("last_sign_in_at").page(params[:page]).per(5)

end

# def sendmail
#   @mail=NoticeMailer.sendmail_confirm(1).deliver
#   render text: "Success!"
# end


private
  def tweet_params
    params.permit(:place, :day, :message)
  end

def move_to_index
   redirect_to action: :index unless user_signed_in?
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show

    user = User.find(params[:id])
    @user = User.find(params[:id])
    @first_name = user.first_name
    @last_name = user.last_name
    @id = user.id


    @tweets = user.tweets.page(params[:page]).per(5).order("day")


     if user.birthday.present? then
       @birthday  = user.birthday
       date_format = "%Y%m%d"
       birthday = @birthday.to_date
       @age  = ((Date.today.strftime(date_format).to_i) -(birthday.strftime(date_format).to_i)) / 10000
      else
       @age=""
      end

  end

  def edit
  end

  def update
     current_user.update(update_params)
  end

  def select
     @user = User.new(sex: 'male')

  end



 # def messages

 #   @message = Message.create(message: params[:message], user_id: params[:user_id])

 #   user = User.find(params[:user_id])

 #   puts 'MessageIDは'
 #   puts @user.id

 #   redirect_to "/users/#{@message.user.id}"

 # end


private
  def update_params
    params.require(:user).permit(:first_name, :last_name, :sex, :birthday, :image, :language1, :language2, :fb, :place)
end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_login_modal.html.erb
<div id="login_modal" class="modal">
  <div class="modal-header">
    <h3>Log in</h3>
    <div class="close">×</div>
  </div>

  <div class="modal-content">
    <%= form_for(:user, url: session_path(:user)) do |f| %>
      <div class="field login-field">
        <%= f.email_field :email, autofocus: true, placeholder: true %>
      </div>

      <div class="field login-field">
        <%= f.password_field :password, autocomplete: "off", placeholder: true %>
      </div>

      <div class="reset-password">
        <%= link_to "Forgot password?", new_password_path(resource_name) %>
      </div>

      <div class="field remember-me">
        <%= f.check_box :remember_me %>
        <%= f.label :remember_me %>
      </div>

      <div class="actions">
        <%= f.submit "Log In", class: 'square-button login' %>
      </div>
    <% end %>

    <div class="divider">
      <hr class="left">or<hr class="right">
    </div>

    <%= link_to user_omniauth_authorize_path(:facebook), class: 'square-button facebook' do %>
      <i class="fa fa-facebook"></i>Continue with Facebook
    <% end %>

    <div class="join-section">
      <p>Don't have an account?</p>

      <%= link_to 'Join', '#', class: 'post signup-link' %>
    </div>
  </div>
</div>

app/views/layouts/_signup_modal.html.erb
<div id="signup_modal" class="modal">
  <div class="modal-header">
    <h3>Sign up</h3>
    <div class="close">×</div>
  </div>

  <div class="modal-content">
    <%= form_for(:user, url: registration_path(:user)) do |f| %>
      <div class="field login-field name">
        <%= f.text_field :first_name, autofocus: true, placeholder: true %>
      </div>

      <div class="field login-field name">
        <%= f.text_field :last_name, placeholder: true %>
      </div>

      <div class="field login-field">
        <%= f.email_field :email, placeholder: true %>
      </div>

      <div class="field login-field">
        <%= f.password_field :password, autocomplete: "off", placeholder: true %>
      </div>

      <div class="actions">
        <%= f.submit "Join with Email", class: 'square-button login' %>
      </div>
    <% end %>

    <div class="divider">
      <hr class="left">or<hr class="right">
    </div>

    <%= link_to user_omniauth_authorize_path(:facebook), class: 'square-button facebook' do %>
      <i class="fa fa-facebook"></i>Join with Facebook
    <% end %>

    <div class="join-section">
      <p>Already a member?</p>

      <%= link_to 'Log in', '#', class: 'post login-link' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<!-- レスポンシブデザイン　ビューポートの設定 -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>

  <title>Brali</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<!-- <<%= javascript_include_tag :defaults %> -->

  <%= csrf_meta_tags %>
  <meta http-equiv="refresh">
</head>

<!-- GoogleのAPI> -->
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=XXXXXXXX&libraries=places&language=en">
  </script>


<script type="text/javascript">
var input = document.getElementById( 'keyword');
    var options = {
        types: ['(cities)'],
    };
    autocomplete = new google.maps.places.Autocomplete( input, options);
</script>



<body>

 <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<header class="header">
    <div class="header__bar row">
      <h1 class="grid-6">
       <ul class="user__info">
        <li><a href="/">Brali</a></li>
        <li><a href="/tweets/timeline">TimeLine </a></li>
      </ul>
      </h1>


<div class="icons mobile">
  <a class="search-icon"></a>
  <a class="user-icon"></a>
</div>

<div class="search desktop">
  <%= form_tag('/tweets/search', method: :get) do %>
  <select name="kind" id="kind">
    <option>Traveler</option>
    <option>Host</option>
  </select>
  <input name="keyword" id="keyword" value="" type="text">
  <input id="btn-search" type="submit" value="">
  </input>
</div>

  <% end %>


<div class="user-login desktop">
  <% if user_signed_in? %>

        <div class="user_nav grid-6">
          <span>
           <%= image_tag current_user.image.url(:small) %>
            <ul class="user_info">
              <li>
                <a href="/users/<%= current_user.id %>">My Page</a>
                  <%= link_to "Log out", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
          <a class="post" href="/tweets/new">POST</a>
        </div>

      <% else %>

        <div class="grid-6">
          <%= render 'layouts/signup_modal' %>
          <%= render 'layouts/login_modal' %>
          <%= link_to 'Log in', '#', class: 'post login-link' %>
          <%= link_to 'Sign up', '#', class: 'post signup-link' %>
        </div>
      <% end %>
</div>

      <!-- <div class="lang">
          <a href="/tweets/english>">English</a>
      </div>
 -->


  </div>
  </header>

<%= yield %>

  </div>

<footer>
    <div class="text-footer">
    <center>
      Tatsuya Takemura All right reserved.
    </center>
    </div>
    </footer>



</body>
</html>

app/views/messages/_message.html.erb
<% if current_user.id == message.user_id || current_user.id == message.sender_id %>

<div class="message">
  <div class="sender-avatar">
    <%= image_tag(message.sender_image.url(:small)) %>
  </div>



  <div class="sender-name">
    <%= link_to(message.sender_first_name, message.sender) %>
  </div>

  <div class="text">
    <%= message.message %>
  </div>

  <div class="created-at">
    <%= message.created_at %>
  </div>
</div>

<% end %>

app/views/messages/index.html.erb
<div class="container">

  <%= form_tag("/users/#{@user.id}/messages", method: :post) do %>
    <textarea cols="30" name="message" placeholder="Comment" rows="2"></textarea>
    <input type="submit" value="SEND">
  <% end %>

  <h1>Past Message</h1>

  <%= render @user.messages %>
</div>

app/views/tweets/create.html.erb
投稿が完了しました！

<br>
  <a href="/tweets">投稿一覧へ戻る！</a>

app/views/tweets/destroy.html.erb
<div class="contents row">
  <div class="sucess">
    <h3>
      delete success!
    </h3>
    <a class="btn" href="/">Return</a>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="contents row">
  <%= form_tag("/tweets/#{@tweet.id}", method: :patch) do %>
    <h3>
     EDIT
   </h3>
   <textarea cols="30" name="message" rows="10"><%=@tweet.message %></textarea>
   <input type="submit" value="SEND">
   <% end %>
 </div>

app/views/tweets/index.html.erb
<!-- GoogleのAPI> -->
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBvhoPfz4HASHTDQGVir2N5CKcwIdshf3M&libraries=places&language=en">
  </script>

<script type="text/javascript">
var input = document.getElementById( 'keyword');
    var options = {
        types: ['(cities)'],
    };
    autocomplete = new google.maps.places.Autocomplete( input, options);
</script>




<div class = "maintitle">
    <P>Brali</p>

</div>

<div class="contents">
<div class="contents1">
<BR><BR>
<h2> Meet new people !</h2>
<p class="text1">
最近、海外からたくさんの観光客が訪問しています。</p>
 <p class="text1">
せっかくだから、交流したいと思っているけど、</p>
<p class="text1">
英語できないし。</p>
 <p class="text1">
なかなか、初めの一歩が踏み出せない。</p>
 <p class="text1">
でも、そんな勇気ないなんて言わないで、</p>
 <p class="text1">
とりあえず、検索してみよう。</p>
 <p class="text1">
誰かが、あなたを待っているはず。</p>
<br>

<div class = "search2">
<%= form_tag('/tweets/search', method: :get) do %>
<select name="kind" id="kind">
    <option>Traveler</option>
    <option>Host</option>
  </select>
<input placeholder="Search: Enter a location" name="keyword" id="keyword2" value="" type="text">

<input id="btn-search" type="submit" value="">
</input>
  </div>
  <% end %>

      </div>


<div class="contents2">
<BR><BR>
<h2> Life is an adventure</h2>
 <p class="text1">
旅行会社が用意したパックツアーにそろそろ飽きた頃</p>
 <p class="text1">
現地の人と交流したい。</p>
<p class="text1">
現地の人しか知らない美味しい店。</p>
<p class="text1">
現地の人しか知らない観光スポット</p>
 <p class="text1">
でも、そんな勇気ないなんて言わないで、</p>
 <p class="text1">
とりあえず、登録してみよう。</p>
 <p class="text1">
新しい世界が広がるはず</p>
<br>


<% unless user_signed_in? %>
<center>
<div class="sign_up2">
 <%= link_to "Sign up", new_user_registration_path, class: 'post' %>
</div>
  </center>
<% end %>

</div>




</body>

app/views/tweets/new.html.erb
<
<!-- < GOOGLE API > -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBvhoPfz4HASHTDQGVir2N5CKcwIdshf3M&libraries=places&sensor=false&language=en">
  </script>



<!-- < GOOGLE API > -->
<script type="text/javascript">
    var input = document.getElementById('place');
    var options = {
        types: ['(cities)'],
    };
    google.maps.event.addDomListener( window, 'load');
    autocomplete = new google.maps.places.Autocomplete( input, options);
</script>



<body>

<!-- 本文 -->
<div class="contents row"> 
  <div class="container">

  <%= form_tag('/tweets', method: :post) do %>
    
  <h3> POST </h3>
    
    <input id="place" type="text" name="place" required>

    <input placeholder="visiting date : yyyy-mm-dd" type="date" name="day" required>

    <textarea cols="30" placeholder="message" name="message" rows="5" required></textarea>
    <input type="submit" value="SEND">

  <% end %>

  </div>
</div>

  </body>

app/views/tweets/search.html.erb
<div class = "contents row">

<% if params[:kind] == "Traveler" %>

  <table BORDER="1" WIDTH="900">

  <div class="list-table">

  <div class="timeline-title">
  <p>Travelers in <%= params[:keyword] %></p>
  </div>

  <% @tweets.each do |tweet| if tweet.day >= Date.today %>

  <tr>
  <td rowspan="7">
  <a href="/users/<%= tweet.user.id %>">
  <div class="timeline-pic">
  <%= image_tag tweet.user.image.url(:medium) %>
  </div>
  </a>
  </td>

  <td><div class="timeline-day">
    <%= tweet.day %></div></td>
  </tr>

  <td><a href="/users/<%= tweet.user.id %>">
  <div class ="timeline-name">
  <%= tweet.user.first_name %>
  <%= tweet.user.last_name %>
  </div>
  </a>
  </td>
  

  <tr><td>From: <%= tweet.user.place %></td>
  </tr>
  <tr>
  <td>Speaks: <%= tweet.user.language1 %></td>
  </tr>
  </tr>
  <tr>
  <td>Visiting: <%= tweet.place %></td>
  </tr>
  
  <tr>
  <td><br><%= tweet.message %></td>
  </tr>

<tr><td>
<br>
<a href="/tweets/<%= tweet.id %>">
<img src="/assets/comment.png" width="120">
  </a>
  </td></tr>
  
   <tr><td colspan="2">
    <BR><HR><BR>
  </td></tr>


  <% end %>
  <% end %>

</table>
<%= paginate(@tweets) %>

  </div>

<% end %>



<% if params[:kind] == "Host" %>

  <table BORDER="1" WIDTH="600">

  <div class="list-table">
<div class="timeline-title">
  <p>Resident in <%= params[:keyword] %></p>
  </div>

  <% @users.each do |user| %>

  <tr>
  <td rowspan="2">
  <a href="/users/<%= user.id %>">
  <%= image_tag user.image.url(:medium) %>
  </a>
  </td>
  <td><a href="/users/<%= user.id %>">
  <div class="timeline-name">
  <%= user.first_name %>
  <%= user.last_name %>
  <div>
  </a>
  </td>
  </tr>


  <tr><td>Residence: <%= user.place %></td>
  </tr>

 <tr><td colspan="2">
    <BR><HR><BR>
  </td></tr>


<% end %>



<% end %>
</table>
<%= paginate(@tweets) %>


</div>

app/views/tweets/show.html.erb
<!-- Tweetへのメッセージ -->
<!-- <!-- !-- 本人ならTweetを削除、修正できる-->


<!-- <!--<% if user_signed_in? && current_user.id == @tweet.user_id %>
<ul class="more_list">
    <li>
      <%= link_to 'Edit',"/tweets/#{@tweet.id}/edit", method: :get %>
      
    </li>
    <li>
      <%= link_to 'Delete',"/tweets/#{@tweet.id}", method: :delete %>
      
    </li>
  </ul>

<% end %>
  -->



<div class="contents row">

<table BORDER="1" WIDTH="900">



<!-- <div class="list-table"> -->

<tr>
  <td rowspan="2">
 <a href="/users/<%= @tweet.user.id %>">
          <%= image_tag @tweet.user.image.url(:thumb) %>
 </a>
 </td>

<td>
    <a href="/users/<%= @tweet.user.id %>">
    <span class="timeline-name">
      <%= @tweet.user.first_name %>
      <%= @tweet.user.last_name %>
    </span>
    </td>
  </tr>

  <tr><td>
  <%= @tweet.message %>
  </td></tr>

</table>
  </div>



  <div class="container">
      <%= form_tag("/tweets/#{@tweet.id}/comments", method: :post) do %>
        <textarea cols="30" name="message" placeholder="Comment" rows="2"></textarea>
        <input type="submit" value="SEND">
      <% end %>

 

<table BORDER="1" WIDTH="500" Aligh="center">
   <div class="comments">

   <center><h4>Comments</h4></center>
     <% if @comments %>
       <% @comments.each do |comment| %>
         <p>
      
      <tr>
      <td>
         <a href="/users/<%= comment.user_id %>">
          <%= image_tag comment.user.image.url(:small) %>
         </a>
          
      </td>

      <td rowspan="2">
        <%= comment.message %>
      </td>
      </tr>

      <tr><td>
       <strong><%= link_to comment.user.first_name,"/users/#{comment.user_id}" %></strong>
     </td></tr>
      
       <tr><td>
       </td>

       <td>
           <%= comment.created_at %>
         </td></tr>

         <tr><td colspan="2">
          <BR><BR>
         </td></tr>

        
        <% end %>
        <% end %>

    </div>

  </div>
  </table>
  </div>

app/views/tweets/timeline.html.erb
<div class= "timeline">

<div class = "contents row">

<table WIDTH="900">

<% @tweets.each do |tweet| if tweet.day >= Date.today %>



<!-- <div class="list-table">  -->


<tr>
<td rowspan="7">
  <a href="/users/<%= tweet.user.id if tweet.user.present? %>">
    <div class="timeline-pic">
      <%= image_tag tweet.user.image.url(:medium) if tweet.user.present? %>
    </div>
  </a>
</td>
 
<td>
<%= tweet.day %>
</td>
</tr>



<td><a href="/users/<%= tweet.user.id if tweet.user.present? %>">
<div class="timeline-name">
<%= tweet.user.first_name if tweet.user.present?%>
<%= tweet.user.last_name if tweet.user.present?%>
</div>
</a>
</td>


<tr><td>From: <%= tweet.user.place if tweet.user.present?%></td>

</tr>

<tr>
<td>Speak: <%= tweet.user.language1 if tweet.user.present?%></td>
</tr>

<tr>
<td>Visiting: <%= tweet.place %></td>
</tr>

<tr>
<td><br><%= tweet.message %></td>
</tr>

<tr><td>
<br>
<a href="/tweets/<%= tweet.id %>">
<img src="/assets/comment.png" width="120">
  </a>
  </td></tr>


  <tr><td colspan="2">
    <BR><HR><BR>
  </td></tr>


</div>

<% end %>


<% end %>


</table>


<%= paginate(@tweets) %>

  

</div>
</div>

app/views/tweets/update.html.erb
<div class = "contents row">
  <div class="success">
  <h3>
    Edit Success
  </h3>
  <a class="btn" href="/">Return</a>
  </div>
  </div>
  

app/views/users/edit.html.erb
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false&language=en"></script>


<div class = "contents row">
  <div class="col-lg-12">
    <%= form_for current_user,
    :html => { :multipart => true } do |f| %>

    <h3>Profile Picture</h3>
      <div class="form-group file">

     <!--  <%= image_tag current_user.image.url if current_user.image.present? %> 
      <%= f.label :image %> 
      <br /> -->
      
      <%= f.file_field :image %>
      </div>

      <h3>Information</h3>
      <div class="form-group">
        <div class="col-lg-6">
        First Name:
        <%= f.text_field :first_name %>
        <br>
        Last Name:
        <%= f.text_field :last_name %>
        <br>

        
        Sex:
        <%= f.select :sex, ['male', 'female','Not specified'],  :include_blank => true %>
<br><br>

        Birthday (YYYY/MM/DD):
        <%= f.text_field :birthday %>
         <!-- 
        <%= f.select :birth_month, [['January',1],'February','Marth','April','May','June','July','August','September','October','November','December'] %>
        <%= f.select :birth_day, 1..31 %>
        <%= f.select :birth_year, (Time.zone.now.year - 120)..(Time.zone.now.year) ,:selected=>(Time.zone.now.year - 25) %>
        -->
       
      </div>

      <div class="form-group">
        <%= f.submit "SEND" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class= "mypage">

<div class = "contents row">

<div class="mypage-left">

  <%= image_tag @user.image.url(:thumb) %>

</div>



<div class="mypage-main">
   <div class="mypage-name">
   <%= @user.first_name %>
   <%= @user.last_name %>
   </h1>
  </div>

<div class="mypage-sex">
  <%= @user.sex %>,<%= @age %>
  </div>



  <a href="/users/<%= @user.id %>/messages">
    <img src="/assets/envelope.svg" width="32">
  </a>

<div class="mypage-place">
  <%= @user.place %>
  </div>
  <br>
  <div class="mypage-language1">
  <%= @user.language1 %>,
  <%= @user.language2 %>
  </div>
  <br>

   <div class="mypage-fb">
     <a href = "<%= @user.fb %>"><%= @user.fb %></a>
     
   </div>
 <% if current_user.id == @id %>
      <div class="profile_edit">
        <%= link_to "Edit", edit_user_path(current_user), {:class => "btn btn-primary withripple" }%>
      </div>
    <% end %>

<br>

  </div>
  

app/views/users/update.html.erb
<div class="contents row">
  <div class="col-lg-12">
    <h3>Success</h3>
    <%= link_to "Return", root_path %>
  </div>
</div>